import Foundation
import XCTest
@testable import GoKit

/// Board hashes cannot be derived by hand, so they are locked in a generated file
/// instead of being asserted inside conformance vectors.
///
/// The lock is a regression guard, not ground truth: it catches either engine
/// silently changing how it hashes a position, which is the failure mode that
/// would break `resume` and desync detection (docs/04 §4.2).
final class ParityLockTests: XCTestCase {
    struct Lock: Codable {
        struct Case: Codable {
            let id: String
            let size: Int
            let black: [String]
            let white: [String]
            let hash: String
        }
        let rulesVersion: String
        let note: String
        let cases: [Case]
    }

    static let lockURL = VectorLoader.vectorsURL
        .deletingLastPathComponent()
        .appendingPathComponent("parity/positions.json")

    /// Deterministic positions spanning every board size, empty through crowded.
    private func buildCases() -> [Lock.Case] {
        var cases: [Lock.Case] = []
        for size in BoardSize.supported {
            for seed in UInt64(1)...12 {
                var generator = SeededGenerator(seed: seed &* UInt64(size))
                var engine = GameEngine.newGame(size: size, rules: .chinese)
                let moveCount = Int(seed) * size
                for _ in 0..<moveCount {
                    guard engine.state.phase == .playing else { break }
                    let legal = engine.legalMoves().sorted { ($0.row, $0.col) < ($1.row, $1.col) }
                    guard let point = legal.randomElement(using: &generator) else { break }
                    engine = (try? engine.apply(.play(point))) ?? engine
                }
                let board = engine.state.board
                cases.append(Lock.Case(
                    id: "size\(size)-seed\(seed)",
                    size: size,
                    black: board.stones(of: .black).map { Coordinate.text($0, size: size) },
                    white: board.stones(of: .white).map { Coordinate.text($0, size: size) },
                    hash: String(format: "0x%016llX", engine.state.boardHash)
                ))
            }
        }
        return cases
    }

    /// Set `WRITE_PARITY_LOCK=1` to regenerate. Regenerating is a deliberate act:
    /// it means accepting whatever the engine now produces.
    func testParityLockMatches() throws {
        let cases = buildCases()

        if ProcessInfo.processInfo.environment["WRITE_PARITY_LOCK"] == "1" {
            let lock = Lock(
                rulesVersion: "1.0.0",
                note: "Generated by GoKit. Every engine must reproduce these hashes exactly.",
                cases: cases
            )
            let encoder = JSONEncoder()
            encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
            try encoder.encode(lock).write(to: Self.lockURL)
            print("wrote \(cases.count) parity cases to \(Self.lockURL.path)")
            return
        }

        let data = try Data(contentsOf: Self.lockURL)
        let lock = try JSONDecoder().decode(Lock.self, from: data)
        XCTAssertEqual(lock.cases.count, cases.count, "parity case count changed")

        for (expected, actual) in zip(lock.cases, cases) {
            XCTAssertEqual(actual.id, expected.id)
            XCTAssertEqual(actual.black, expected.black, "\(expected.id): black stones")
            XCTAssertEqual(actual.white, expected.white, "\(expected.id): white stones")
            XCTAssertEqual(actual.hash, expected.hash, "\(expected.id): board hash")
        }
    }

    /// The stone lists in the lock must hash to the recorded value on their own,
    /// so another engine can verify without replaying any moves.
    func testLockedPositionsRehashFromStonesAlone() throws {
        let lock = try JSONDecoder().decode(Lock.self, from: Data(contentsOf: Self.lockURL))
        for entry in lock.cases {
            let engine = GameEngine.position(
                size: entry.size,
                black: entry.black.compactMap { Coordinate.point($0, size: entry.size) },
                white: entry.white.compactMap { Coordinate.point($0, size: entry.size) }
            )
            XCTAssertEqual(String(format: "0x%016llX", engine.state.boardHash), entry.hash, entry.id)
        }
    }
}
