package rules

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"
)

// The parity lock is the real cross-engine proof. Board hashes cannot be derived
// by hand, so instead of asserting them inside vectors they are locked in a file
// generated by one engine and verified by every other. It catches an engine
// silently changing how it hashes a position, which is what would break resume and
// desync detection (docs/04 §4.2).

type parityLock struct {
	RulesVersion string `json:"rulesVersion"`
	Note         string `json:"note"`
	Cases        []struct {
		ID    string   `json:"id"`
		Size  int      `json:"size"`
		Black []string `json:"black"`
		White []string `json:"white"`
		Hash  string   `json:"hash"`
	} `json:"cases"`
}

func TestParityLock(t *testing.T) {
	path := filepath.Join(specRoot(t), "parity", "positions.json")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	var lock parityLock
	if err := json.Unmarshal(data, &lock); err != nil {
		t.Fatalf("parsing %s: %v", path, err)
	}
	if len(lock.Cases) == 0 {
		t.Fatal("parity lock is empty")
	}

	for _, entry := range lock.Cases {
		t.Run(entry.ID, func(t *testing.T) {
			parse := func(list []string) []Point {
				out := make([]Point, 0, len(list))
				for _, text := range list {
					p, ok := ParseCoordinate(text, entry.Size)
					if !ok {
						t.Fatalf("bad coordinate %q for %dx%d", text, entry.Size, entry.Size)
					}
					out = append(out, p)
				}
				return out
			}
			engine := Position(PositionOptions{
				Size:  entry.Size,
				Black: parse(entry.Black),
				White: parse(entry.White),
			})
			got := fmt.Sprintf("0x%016X", engine.State.BoardHash)
			if got != entry.Hash {
				t.Errorf("board hash: want %s, got %s", entry.Hash, got)
			}
		})
	}
	t.Logf("verified %d locked positions against rules_version %s", len(lock.Cases), lock.RulesVersion)
}
