#!/usr/bin/env python3
"""Generate the shared Zobrist table and the per-language source files.

The table is part of the rules specification: both engines must XOR the same
constants or their board hashes cannot be compared. Regenerating it is a
breaking change -- bump rules-spec/VERSION when you do.
"""
import json
import pathlib

MASK = (1 << 64) - 1
SEED = 0x5EE7E0A1D0C0FFEE
MAX_POINTS = 19 * 19


def splitmix64(state):
    """Deterministic 64-bit PRNG; identical output on every platform."""
    while True:
        state = (state + 0x9E3779B97F4A7C15) & MASK
        z = state
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK
        yield z ^ (z >> 31)


def main():
    root = pathlib.Path(__file__).resolve().parents[2]
    rng = splitmix64(SEED)
    black = [next(rng) for _ in range(MAX_POINTS)]
    white = [next(rng) for _ in range(MAX_POINTS)]

    payload = {
        "version": (root / "rules-spec" / "VERSION").read_text().strip(),
        "algorithm": "splitmix64",
        "seed": hex(SEED),
        "index": "row * boardSize + col, row 0 = top",
        "black": [f"0x{v:016X}" for v in black],
        "white": [f"0x{v:016X}" for v in white],
    }
    out = root / "rules-spec" / "zobrist_table.json"
    out.write_text(json.dumps(payload, indent=1) + "\n")

    def rows(values, per_line=4):
        lines = []
        for i in range(0, len(values), per_line):
            lines.append("    " + " ".join(f"0x{v:016X}," for v in values[i:i + per_line]))
        return "\n".join(lines)

    swift = f"""// Generated by rules-spec/tools/gen_zobrist.py -- do not edit by hand.
// Source of truth: rules-spec/zobrist_table.json (rules_version {payload["version"]}).

extension Zobrist {{
  static let blackTable: [UInt64] = [
{rows(black)}
  ]

  static let whiteTable: [UInt64] = [
{rows(white)}
  ]
}}
"""
    (root / "sente-ios" / "Packages" / "GoKit" / "Sources" / "GoKit" / "Zobrist+Table.swift").write_text(swift)

    def go_rows(values, per_line=4):
        lines = []
        for i in range(0, len(values), per_line):
            lines.append("\t" + " ".join(f"0x{v:016X}," for v in values[i:i + per_line]))
        return "\n".join(lines)

    go = f"""// Code generated by rules-spec/tools/gen_zobrist.py. DO NOT EDIT.
// Source of truth: rules-spec/zobrist_table.json (rules_version {payload["version"]}).

package rules

var blackTable = [{MAX_POINTS}]uint64{{
{go_rows(black)}
}}

var whiteTable = [{MAX_POINTS}]uint64{{
{go_rows(white)}
}}
"""
    (root / "sente-server" / "internal" / "rules" / "zobrist_table.go").write_text(go)

    print(f"wrote {out.relative_to(root)}, Zobrist+Table.swift and zobrist_table.go "
          f"({MAX_POINTS} points x 2 colours)")


if __name__ == "__main__":
    main()
