#!/usr/bin/env python3
"""Write the conformance vectors.

Every expectation here is authored by hand from docs/02-go-rules-spec.md. Nothing
is derived from an engine -- a vector generated by the code it tests proves nothing.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2] / "rules-spec" / "vectors"


def vector(group, vid, **fields):
    body = {"id": vid}
    body.update(fields)
    path = ROOT / group / f"{vid}.json"
    path.write_text(json.dumps(body, indent=2, ensure_ascii=False) + "\n")


def setup(black=(), white=()):
    return {"black": list(black), "white": list(white)}


# ─────────────────────────── legality ───────────────────────────
vector("legality", "empty-point-is-legal",
       description="Any empty intersection on an empty board is playable.",
       rules="japanese", board_size=9, setup=setup(), to_play="black",
       move="e5", expect={"legal": True, "captured": []})

vector("legality", "occupied-point-is-rejected",
       description="A stone already sits on e5.",
       rules="japanese", board_size=9, setup=setup(black=["e5"]), to_play="white",
       move="e5", expect={"legal": False, "reason": "occupied"})

vector("legality", "off-board-point-is-rejected",
       description="Row 10 does not exist on a 9x9 board.",
       rules="japanese", board_size=9, setup=setup(), to_play="black",
       move="e10", expect={"legal": False, "reason": "out_of_bounds"})

vector("legality", "playing-out-of-turn-is-rejected",
       description="Black is to play; White may not move.",
       rules="japanese", board_size=9, setup=setup(), to_play="black",
       move="e5", move_by="white", expect={"legal": False, "reason": "not_your_turn"})

vector("legality", "corner-point-is-legal",
       description="Corners have two liberties, which is enough.",
       rules="japanese", board_size=9, setup=setup(), to_play="black",
       move="a1", expect={"legal": True, "captured": []})

vector("legality", "pass-is-always-legal-while-playing",
       description="Passing needs no board conditions.",
       rules="japanese", board_size=9, setup=setup(), to_play="black",
       move="pass", expect={"legal": True, "phase": "playing"})

vector("legality", "two-passes-enter-scoring",
       description="Two consecutive passes end play and open the scoring phase.",
       rules="japanese", board_size=9, setup=setup(), to_play="black",
       moves=["B:pass"], move="pass", expect={"legal": True, "phase": "scoring"})

vector("legality", "no-moves-after-two-passes",
       description="Once scoring has started, plays are rejected.",
       rules="japanese", board_size=9, setup=setup(), to_play="black",
       moves=["B:pass", "W:pass"], move="e5",
       expect={"legal": False, "reason": "game_not_playing"})

vector("legality", "resign-finishes-the-game",
       description="Black resigns; White wins without counting.",
       rules="japanese", board_size=9, setup=setup(), to_play="black",
       move="resign",
       expect={"legal": True, "phase": "finished",
               "result": {"winner": "white", "reason": "resignation"}})

# ─────────────────────────── capture ───────────────────────────
vector("capture", "single-stone-in-the-centre",
       description="White e5 loses its last liberty when Black plays f5.",
       rules="japanese", board_size=9,
       setup=setup(black=["e6", "e4", "d5"], white=["e5"]), to_play="black",
       move="f5",
       expect={"legal": True, "captured": ["e5"], "captures_after": {"black": 1, "white": 0}})

vector("capture", "single-stone-in-the-corner",
       description="A corner stone has only two liberties.",
       rules="japanese", board_size=9,
       setup=setup(black=["a2"], white=["a1"]), to_play="black",
       move="b1",
       expect={"legal": True, "captured": ["a1"], "captures_after": {"black": 1, "white": 0}})

vector("capture", "two-chains-with-one-move",
       description="e5 removes the liberty shared by two separate white stones.",
       rules="japanese", board_size=9,
       setup=setup(black=["c5", "d6", "d4", "g5", "f6", "f4"], white=["d5", "f5"]),
       to_play="black", move="e5",
       expect={"legal": True, "captured": ["d5", "f5"], "captures_after": {"black": 2, "white": 0}})

vector("capture", "three-stone-chain",
       description="A whole chain dies at once when its last liberty is filled.",
       rules="japanese", board_size=9,
       setup=setup(black=["c5", "g5", "d6", "e6", "f6", "d4", "e4"],
                   white=["d5", "e5", "f5"]),
       to_play="black", move="f4",
       expect={"legal": True, "captured": ["d5", "e5", "f5"],
               "captures_after": {"black": 3, "white": 0}})

vector("capture", "capture-count-accumulates",
       description="Prisoners add to the count already held.",
       rules="japanese", board_size=9,
       setup=setup(black=["e6", "e4", "d5"], white=["e5"]), to_play="black",
       captures={"black": 4, "white": 2}, move="f5",
       expect={"legal": True, "captured": ["e5"], "captures_after": {"black": 5, "white": 2}})

# ─────────────────────────── suicide ───────────────────────────
vector("suicide", "single-stone-suicide-rejected",
       description="e5 would have no liberties and captures nothing.",
       rules="japanese", board_size=9,
       setup=setup(white=["d5", "f5", "e6", "e4"]), to_play="black",
       move="e5", expect={"legal": False, "reason": "suicide"})

vector("suicide", "connecting-into-a-dead-chain-is-suicide",
       description="Joining d5 leaves the two-stone chain without liberties.",
       rules="japanese", board_size=9,
       setup=setup(black=["d5"], white=["c5", "d6", "d4", "e6", "e4", "f5"]),
       to_play="black", move="e5", expect={"legal": False, "reason": "suicide"})

vector("suicide", "capturing-first-makes-the-move-legal",
       description=("The classic case: e5 looks like suicide, but it takes d5 and the "
                    "freed point becomes its liberty. Checking suicide before removing "
                    "captures is the most common engine bug."),
       rules="japanese", board_size=9,
       setup=setup(black=["c5", "d6", "d4"], white=["d5", "e6", "e4", "f5"]),
       to_play="black", move="e5",
       expect={"legal": True, "captured": ["d5"], "captures_after": {"black": 1, "white": 0}})

vector("suicide", "suicide-rejected-under-chinese-rules-too",
       description="Neither supported ruleset permits suicide.",
       rules="chinese", board_size=9,
       setup=setup(white=["d5", "f5", "e6", "e4"]), to_play="black",
       move="e5", expect={"legal": False, "reason": "suicide"})

# ─────────────────────────── ko ───────────────────────────
KO_BLACK = ["c5", "d6", "d4", "e5"]
KO_WHITE = ["e6", "e4", "f5"]

vector("ko", "immediate-recapture-is-forbidden",
       description="White takes the ko at d5; Black may not take it straight back.",
       rules="japanese", board_size=9,
       setup=setup(black=KO_BLACK, white=KO_WHITE), to_play="white",
       moves=["W:d5"], move="e5", expect={"legal": False, "reason": "ko"})

vector("ko", "the-ko-capture-itself-is-legal",
       description="White d5 captures exactly one stone and sets the ko point.",
       rules="japanese", board_size=9,
       setup=setup(black=KO_BLACK, white=KO_WHITE), to_play="white",
       move="d5",
       expect={"legal": True, "captured": ["e5"], "ko_point": "e5",
               "captures_after": {"black": 0, "white": 1}})

vector("ko", "recapture-allowed-after-a-ko-threat",
       description="A threat and its answer clear the ko point.",
       rules="japanese", board_size=9,
       setup=setup(black=KO_BLACK, white=KO_WHITE), to_play="white",
       moves=["W:d5", "B:a1", "W:a2"], move="e5",
       expect={"legal": True, "captured": ["d5"], "captures_after": {"black": 1, "white": 1}})

vector("ko", "no-ko-point-when-several-stones-are-taken",
       description="Ko only arises from a single-stone recapture shape.",
       rules="japanese", board_size=9,
       setup=setup(black=["c5", "g5", "d6", "e6", "f6", "d4", "e4"],
                   white=["d5", "e5", "f5"]),
       to_play="black", move="f4",
       expect={"legal": True, "ko_point_absent": True})

vector("ko", "chinese-rules-reject-the-recapture-as-superko",
       description=("Same position, different rule: Chinese has no basic ko, so the "
                    "repeat is caught by positional superko and reported as such."),
       rules="chinese", board_size=9,
       setup=setup(black=KO_BLACK, white=KO_WHITE), to_play="white",
       moves=["W:d5"], move="e5", expect={"legal": False, "reason": "superko"})

# ─────────────────────────── superko ───────────────────────────
vector("superko", "starting-position-is-in-the-history",
       description=("The empty board counts as a seen position, so a move that "
                    "recreated it would be refused. Guards against engines that "
                    "only start recording after the first move."),
       rules="chinese", board_size=9, setup=setup(), to_play="black",
       expect={"history_contains_start": True})

vector("superko", "passing-does-not-record-a-position",
       description="A pass leaves the board unchanged and must not grow the history.",
       rules="chinese", board_size=9, setup=setup(black=["e5"]), to_play="white",
       moves=["W:pass"], expect={"history_size": 1})

# ─────────────────────────── life_death (Benson) ───────────────────────────
vector("life_death", "two-eyed-corner-group-is-pass-alive",
       description="Eyes at a9 and c9 make the chain unconditionally alive.",
       rules="japanese", board_size=9,
       setup=setup(black=["b9", "d9", "a8", "b8", "c8", "d8"]), to_play="black",
       expect={"pass_alive": {"black": ["b9", "d9", "a8", "b8", "c8", "d8"], "white": []}})

vector("life_death", "one-eyed-group-is-not-pass-alive",
       description="Filling c9 leaves a single eye, which Benson rejects.",
       rules="japanese", board_size=9,
       setup=setup(black=["b9", "c9", "d9", "a8", "b8", "c8", "d8"]), to_play="black",
       expect={"pass_alive": {"black": [], "white": []}})

vector("life_death", "lone-stone-is-not-pass-alive",
       description="A single stone on an open board can always be captured.",
       rules="japanese", board_size=9, setup=setup(black=["e5"]), to_play="black",
       expect={"pass_alive": {"black": [], "white": []}})

# ─────────────────────────── scoring ───────────────────────────
HALF_POINT_BLACK = ["d9", "d8", "d7", "e6", "e5", "d4", "d3", "d2", "d1", "b7", "b4", "c2"]
HALF_POINT_WHITE = ["e9", "e8", "e7", "f6", "f5", "e4", "e3", "e2", "e1", "g7", "h5", "g3",
                    "b2", "b1"]

vector("scoring", "japanese-half-point-game",
       description=("Black owns the left, White the right. The two dead white stones "
                    "in Black's corner become prisoners and their points become "
                    "territory. White wins by half a point."),
       rules="japanese", board_size=9, komi=6.5,
       setup=setup(black=HALF_POINT_BLACK, white=HALF_POINT_WHITE),
       dead_stones=["b2", "b1"], captures={"black": 12, "white": 3},
       expect={"territory": {"black": 26, "white": 31},
               "score": {"black": 40, "white": 40.5},
               "winner": "white", "margin": 0.5})

vector("scoring", "chinese-area-on-the-same-position",
       description=("Area counting on the identical position: stones on the board plus "
                    "surrounded points, prisoners ignored. The totals differ from the "
                    "Japanese result, which is the point of the vector."),
       rules="chinese", board_size=9, komi=7.5,
       setup=setup(black=HALF_POINT_BLACK, white=HALF_POINT_WHITE),
       dead_stones=["b2", "b1"], captures={"black": 12, "white": 3},
       expect={"territory": {"black": 26, "white": 31},
               "area": {"black": 38, "white": 43},
               "score": {"black": 38, "white": 50.5},
               "winner": "white"})

vector("scoring", "region-touching-both-colours-is-neutral",
       description=("Column E borders black on one side and white on the other, so it "
                    "scores for nobody. The same rule is what makes seki come out right."),
       rules="japanese", board_size=9, komi=6.5,
       setup=setup(black=["d1", "d2", "d3", "d4", "d5", "d6", "d7", "d8", "d9"],
                   white=["f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9"]),
       expect={"territory": {"black": 27, "white": 27}, "neutral": 9,
               "score": {"black": 27, "white": 33.5}})

vector("scoring", "empty-board-scores-only-komi",
       description="No stones means no territory: the whole board is neutral.",
       rules="japanese", board_size=9, komi=6.5, setup=setup(),
       expect={"territory": {"black": 0, "white": 0}, "neutral": 81,
               "score": {"black": 0, "white": 6.5}})

# ─────────────────────────── handicap ───────────────────────────
for count, stones, size in [
    (2, ["q16", "d4"], 19),
    (4, ["q16", "d4", "q4", "d16"], 19),
    (5, ["q16", "d4", "q4", "d16", "k10"], 19),
    (6, ["q16", "d4", "q4", "d16", "d10", "q10"], 19),
    (9, ["q16", "d4", "q4", "d16", "d10", "q10", "k4", "k16", "k10"], 19),
    (2, ["g7", "c3"], 9),
    (4, ["g7", "c3", "g3", "c7"], 9),
    (6, ["k10", "d4", "k4", "d10", "d7", "k7"], 13),
]:
    vector("handicap", f"handicap-{count}-on-{size}x{size}",
           description=f"{count} stones on {size}x{size}; White moves first and komi drops to 0.5.",
           rules="japanese", board_size=size, handicap=count,
           expect={"handicap_stones": stones, "to_play": "white", "komi": 0.5,
                   "move_number": 0})

# ─────────────────────────── sgf ───────────────────────────
vector("sgf", "round-trip-short-game",
       description="Encoding then decoding must preserve size, komi, rules and moves.",
       rules="japanese", board_size=19, komi=6.5,
       moves=["B:q16", "W:d4", "B:pass", "W:pass"],
       expect={"sgf_contains": ["SZ[19]", "KM[6.5]", "RU[Japanese]", ";B[pd]", ";W[dp]", ";B[]"],
               "round_trip": True})

vector("sgf", "round-trip-handicap-game",
       description="Handicap stones ride in AB and must survive the round trip.",
       rules="chinese", board_size=9, handicap=4,
       moves=["W:e5"],
       expect={"sgf_contains": ["HA[4]", "AB[", "RU[Chinese]", ";W[ee]"],
               "round_trip": True})

vector("sgf", "coordinates-use-the-sgf-origin",
       description=("SGF counts rows from the top; display coordinates count from the "
                    "bottom. q16 on 19x19 is pd, and d4 is dp."),
       rules="japanese", board_size=19,
       moves=["B:q16", "W:d4"],
       expect={"sgf_contains": [";B[pd]", ";W[dp]"], "round_trip": True})

count = sum(1 for _ in ROOT.rglob("*.json"))
print(f"wrote {count} vectors across {len(list(ROOT.iterdir()))} groups")
